import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';
import { Toaster } from 'react-hot-toast';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Jornada do Herói',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta name='viewport' content='initial-scale=1, width=device-width' />
      <body className={manrope.className}>
        <ThemeRegistry>
          {children}
          <Toaster />
        </ThemeRegistry>
      </body>
    </html>
  );
}
